import Navbar from '@/components/ui/navBar';
import Providers from '@/components/logic/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <body className="w-screen h-screen overflow-hidden">
      <Providers>
        <Navbar />
        <main className="h-full bg-background flex flex-col items-center">{children}</main>
      </Providers>
    </body>
  );
}
