import Navbar from '@/components/ui/navBar';
import './globals.css';
import Providers from '@/components/logic/providers';
import { ThemeProvider } from '@/components/logic/theme-provider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
