import Navbar from '@/components/ui/navBar';
import './globals.css';
import Providers from '@/components/logic/providers';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="w-screen min-h-screen overflow-hidden">
        <Providers>
          <Navbar />
          <main className="min-h-screen bg-base-100 flex flex-col items-center">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
